version: 0.2

phases:
  build:
    commands:
	- echo Build started on `date`
	- mkdir build
	- cd build
	- cmake ..
	- make
  post_build:
    commands:
       - echo Build completed

artifacts:
    files:
	- ./main